### ISSUE TITLE
Unreal Menu setup , parent_p

### ISSUE THREAD

**Issue by JLHayde** [hannesdelbeke/unimenu#54] opened 2023-07-22 14:15 UTC
I pulled in latest in into the unreal context menu branch  and got this error.  and check out this main branch to make sure, and i'm getting this issue. The root menu is created in the window/Context menu but none of the submenus & actions are created.
I ran the any_dcc_sample(changed the label to bypass the exception from duplicated name) and get this.
https://github.com/hannesdelbeke/unimenu/blob/d162029b2fc9972b1d2a33f2468dd28c4bedefa0/unimenu/apps/unreal.py#L87

```LogPython: Error: Traceback (most recent call last):
LogPython: Error:   File "D:/Users/Hayden/Programming/studiolauncher/sample_config/unreal-engine/init_unreal.py", line 55, in <module>
LogPython: Error:     app_menu_node = unimenu.setup(MainToolbar,backlink=False)
LogPython: Error:   File "D:\Users\Hayden\Programming\fromGit\unimenu\unimenu\core.py", line 139, in setup
LogPython: Error:     app_node = menu_node.setup(parent_app_node=parent_app_node, backlink=backlink)
LogPython: Error:   File "D:\Users\Hayden\Programming\fromGit\unimenu\unimenu\apps\unreal.py", line 18, in setup
LogPython: Error:     super().setup(parent_app_node=parent_app_node, backlink=backlink)
LogPython: Error:   File "D:\Users\Hayden\Programming\fromGit\unimenu\unimenu\apps\_abstract.py", line 222, in setup
LogPython: Error:     item.setup(parent_app_node=self.app_node)
LogPython: Error:   File "D:\Users\Hayden\Programming\fromGit\unimenu\unimenu\apps\unreal.py", line 18, in setup
LogPython: Error:     super().setup(parent_app_node=parent_app_node, backlink=backlink)
LogPython: Error:   File "D:\Users\Hayden\Programming\fromGit\unimenu\unimenu\apps\_abstract.py", line 217, in setup
LogPython: Error:     self.app_node = self._setup_menu_item(parent_app_node=parent_app_node)
LogPython: Error:   File "D:\Users\Hayden\Programming\fromGit\unimenu\unimenu\apps\unreal.py", line 38, in _setup_menu_item
LogPython: Error:     if not self.check_unique_name():
LogPython: Error:   File "D:\Users\Hayden\Programming\fromGit\unimenu\unimenu\apps\unreal.py", line 78, in check_unique_name
LogPython: Error:     exists = unreal_menus.find_menu(self.get_name_path())
LogPython: Error:   File "D:\Users\Hayden\Programming\fromGit\unimenu\unimenu\apps\unreal.py", line 92, in get_name_path
LogPython: Error:     return self.parent_path + "." + self.id
LogPython: Error: TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

it seems as if at this check, the parent path has been set yet?

**Comment by hannesdelbeke** [comment] 2023-07-22 14:38
Thanks, will have a look. looks like parent path is None and the code is not handling it well.
Caused by fix for https://github.com/hannesdelbeke/unimenu/issues/50

**Comment by hannesdelbeke** [comment] 2023-07-23 11:06
this should be fixed now

**Closed by hannesdelbeke** 2023-07-23 11:06 UTC

**Comment by JLHayde** [comment] 2023-07-24 08:44
Thanks, working for me too
